AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'eks-node-drainer

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: eks-node-drainer
    Description: Safely drain EKS node during cloudformation updates (autoscaling
      groups)
    Author: Chris Williams
    SpdxLicenseId: MIT
    LicenseUrl: s3://eks-node-drainer-sar/da6bd1a60b842c289505a3f4330449da
    ReadmeUrl: s3://eks-node-drainer-sar/27d05bad2a814bfa73bcb9232cfdfc8d
    Labels:
    - eks
    - node
    - drain
    HomePageUrl: https://techblog.chrilliams.co.uk/eks-safe-node-draining
    SemanticVersion: 1.3.1
    SourceCodeUrl: https://github.com/chrilliams/eks-node-drainer
Parameters:
  SecurityGroup:
    Type: String
    Default: ''
    Description: Security Group for Node Drainer lambda, this needs access to the
      Kube API.
  Subnet:
    Type: String
    Default: ''
    Description: Subnet for Node Drainer lambda
  TargetGroup:
    Type: String
    Default: ''
    Description: Target group that we will deregister instances
Globals:
  Function:
    Timeout: 900
Conditions:
  NoVPC:
    Fn::Equals:
    - Ref: SecurityGroup
    - ''
  NoTargetGroup:
    Fn::Equals:
    - Ref: TargetGroup
    - ''
Resources:
  EKSNodeDrainerFunction:
    Type: AWS::Serverless::Function
    DependsOn: EKSNodeDrainerExecutionPolicy
    Properties:
      CodeUri: s3://eks-node-drainer-sar/4bfde8e4e15999d7f8ff39a115c0b63a
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Role:
        Fn::GetAtt:
        - EKSNodeDrainerExecutionRole
        - Arn
      Environment:
        Variables:
          targetGroup:
            Ref: TargetGroup
      VpcConfig:
        Fn::If:
        - NoVPC
        - Ref: AWS::NoValue
        - SecurityGroupIds:
          - Ref: SecurityGroup
          SubnetIds:
          - Ref: Subnet
      Events:
        EKSNodeDrainer:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.autoscaling
              detail-type:
              - EC2 Instance-terminate Lifecycle Action
        EKSRebalance:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.ec2
              detail-type:
              - EC2 Instance Rebalance Recommendation
        EKSInterruption:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
              - aws.ec2
              detail-type:
              - EC2 Spot Instance Interruption Warning
    Metadata:
      SamResourceId: EKSNodeDrainerFunction
  EKSNodeDrainerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
    Metadata:
      SamResourceId: EKSNodeDrainerExecutionRole
  EKSNodeDrainerExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EKSNodeDrainerRolePolicy
      Roles:
      - Ref: EKSNodeDrainerExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
          - eks:DescribeCluster
          Resource:
            Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/*
        - Effect: Allow
          Action:
          - sts:GetCallerIdentity
          - ec2:DescribeInstances
          - autoscaling:CompleteLifecycleAction
          - autoscaling:TerminateInstanceInAutoScalingGroup
          - ec2:CreateNetworkInterface
          - ec2:DeleteNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DetachNetworkInterface
          Resource: '*'
        - Fn::If:
          - NoTargetGroup
          - Ref: AWS::NoValue
          - Effect: Allow
            Action:
            - elasticloadbalancing:DeregisterTargets
            Resource:
            - Ref: TargetGroup
    Metadata:
      SamResourceId: EKSNodeDrainerExecutionPolicy
Outputs:
  EKSNodeDrainerExecutionRoleName:
    Value:
      Fn::GetAtt:
      - EKSNodeDrainerExecutionRole
      - Arn
